PrivateBin/helm-chart

.travis.yml, README.md, Rakefile
Manually updated the gh-pages branch for now until we decide if we're doing it with CI or not
=> Update files for new repo location

Rakefile
This copies README.md to the gh-pages branch so it will display on hub.helm.sh
=> Add Readme gh-pages branch

README.md, privatebin/Chart.yaml, privatebin/templates/service.yaml, privatebin/values.yaml
Allows setting LoadBalancerSourceRanges optionally for the service. Closes #17
=> Optional LoadBalancerSourceRanges

README.md, privatebin/Chart.yaml, privatebin/templates/statefulset.yaml, privatebin/values.yaml
Hi,
added statefulset template with volumeClaimTemplate and few options to manage the persistent storage
=> added statefulset with pvc configuration

privatebin/templates/deployment.yaml
=> update statefulset.yaml template

privatebin/Chart.yaml, privatebin/templates/deployment.yaml, privatebin/values.yaml
PrivateBin 1.3.4 got released and we changed the default exposed port a while ago in the docker image.
=> Update deployed image version and exposed port

privatebin/Chart.yaml, privatebin/templates/ingress.yaml
Updates Ingress API version for version compatibility.
=> Update Ingress API Version

privatebin/Chart.yaml, privatebin/templates/deployment.yaml
See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#deploymentspec-v1-apps, it doesn't even exist in the specification...
Fixes #26
=> Delete service name that should not have existed

privatebin/Chart.yaml, privatebin/templates/_helpers.tpl, privatebin/templates/psp.yaml, privatebin/templates/role.yaml, privatebin/templates/rolebinding.yaml, privatebin/templates/serviceaccount.yaml, privatebin/values.yaml
To allow the chart to support PSP. This complements https://github.com/PrivateBin/helm-chart/pull/32
=> add psp support

.github/workflows/chart-testing.yaml
update the kubernetes versions we test
=> update tested k8s versions

charts/privatebin/Chart.yaml, charts/privatebin/templates/NOTES.txt, charts/privatebin/templates/ingress.yaml
Should close #47 
Better check on 1.21 and lower, since i only tested it on 1.22
=> Add v1 ingress support

charts/privatebin/Chart.yaml, charts/privatebin/templates/statefulset.yaml
Removed the duplicate `serviceName` from the StatefulSet.
=> Remove duplicate serviceName

charts/privatebin/Chart.yaml, charts/privatebin/templates/statefulset.yaml
=> Add support for Statefulset replicas

charts/privatebin/Chart.yaml, charts/privatebin/templates/ingress.yaml, charts/privatebin/values.yaml
=> allow-overriding-pathtype

README.md, charts/privatebin/Chart.yaml, charts/privatebin/templates/deployment.yaml, charts/privatebin/values.yaml
Add an emptyDir option. It might better handle writing action by writing on a filesystem instead of writing on Docker layer.
=> Add emptyDir option

charts/privatebin/Chart.yaml
=> feat(core): Upgrade PrivateBin to 1.5.1

charts/privatebin/Chart.yaml
Release notes: https://github.com/PrivateBin/PrivateBin/releases/tag/1.6.0
=> chore(privatebin): set default version of Privatebin to 1.6.0

charts/privatebin/Chart.yaml
from the checklist this was missing
https://github.com/PrivateBin/PrivateBin/wiki/Release-Checklist
=> Update helm chart version

charts/privatebin/Chart.yaml, charts/privatebin/templates/deployment.yaml, charts/privatebin/values.yaml
Manage deployment security context and pod security context from values.yaml 
In some cluster context you need to specify others values like seccompProfile, drop capabilities or runAsNonRoot
=> Manage securityContext and podSecurityContext from values.yaml file

charts/privatebin/Chart.yaml
=> Upgrade PrivateBin to 1.7.3

README.md, charts/privatebin/Chart.yaml, charts/privatebin/templates/deployment.yaml, charts/privatebin/values.yaml
Add configuration to support topology spread constraints.
=> feat: Add support for topology spread constraints.
